sql_endpoints:

  target: databricks

  outputs:
     
     snowflake:
        type: snowflake
        account: {ENTER_YOUR_ACCT_ID_HERE}
        user: {ENTER_YOUR_USER_ID_HERE}
        password: {ENTER_YOUR_PASSWORD_HERE}
        role : {ENTER_YOUR_ROLE_HERE}
        warehouse: {ENTER_YOUR_WH_HERE}
        database: {ENTER_YOUR_DATABASE_HERE}
        schema: {ENTER_YOUR_SCHEMA_HERE}
        threads: 21
     
     databricks:
         type: databricks
         method: http
         host: {ENTER_YOUR_HOST_HERE}
         token: {ENTER_YOUR_TOKEN_HERE}
         http_path: /sql/1.0/warehouses/{ENTER_YOUR_WH_ID_HERE}
         catalog: {ENTER_YOUR_CATALOG_HERE}
         schema: {ENTER_YOUR_SCHEMA_HERE}
         threads: 21
